# -*- coding: utf-8 -*-
"""UAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHcYRNZlqLZBpg2k0S99XaOVGnzR2p3z
"""

#Installation

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

!nvidia-smi

import torch
torch.cuda.is_available()

import tensorflow as tf
tf.test.gpu_device_name()

import torch
x = torch.rand(5, 3)
print(x)

